
import localFont from "next/font/local";
import "./globals.css";
import Loading from "./loading.js";
import { Suspense } from "react";
import CommonLayout from "@/components/common-layout";
import { Toaster } from "@/components/ui/toaster";
import {
  ClerkProvider,
} from '@clerk/nextjs'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "clerk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <Suspense fallback={<Loading/>}>
          <CommonLayout children={children}/>
        </Suspense>
          <Toaster/>
      </body>
    </html>
    </ClerkProvider>
  );
}
