import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import NotFound from "./not-found";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Auth-next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<NotFound/>}>

        {children}
        </Suspense>
        </body>
    </html>
  );
}
